In [3]:
pip install numpy

     ---------------------------------------- 15.0/15.0 MB 1.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
myList = [1,2,3]

In [6]:
type(myList)

list

In [7]:
np.array(myList)

array([1, 2, 3])

In [8]:
myMatrix = [[1,2,4],[5,6,7],[8,9,10],[11,12,13]]

In [9]:
myMat = np.array(myMatrix)

In [10]:
myMat

array([[ 1,  2,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(3,3)

array([[0.9037858 , 0.52048004, 0.1422917 ],
       [0.71632607, 0.86295692, 0.24311894],
       [0.60864798, 0.54409364, 0.06057518]])

In [22]:
np.random.rand(3,3)

array([[0.80097041, 0.823819  , 0.90549365],
       [0.36063396, 0.71198299, 0.24917872],
       [0.19578675, 0.05924212, 0.47277029]])

In [23]:
np.random.rand()

0.8729593628123486

In [24]:
np.random.rand(1)

array([0.05644253])

In [25]:
np.random.randn(3,3)

array([[-0.05090869, -1.41718407, -0.3867676 ],
       [-1.26456278,  0.45265238, -1.20408737],
       [ 0.77001655,  0.29015842, -0.08762921]])

In [26]:
np.random.randn()

-0.2610720603543976

In [27]:
np.random.randn(2)

array([-0.55602885,  0.63030643])

In [10]:
np.random.randn(5,5)

array([[-0.97601676, -0.16763179, -1.23093159,  2.11239184,  0.54121282],
       [ 0.87118241, -0.62942493,  0.50332064, -0.55041079,  0.09704916],
       [ 0.44488153,  0.31543121,  0.46032511, -0.51031029, -0.182098  ],
       [ 0.57737826, -0.02864992,  0.66426856,  1.10574788,  1.29971672],
       [-1.23451087, -0.18236857, -0.15508199,  0.23444102, -0.28105916]])

In [29]:
np.random.randint

<function RandomState.randint>

In [13]:
np.random.randint(0,100)

61

In [31]:
np.random.randint(0,100,size=(5,5))

array([[ 2, 86, 53, 22, 52],
       [75, 30, 74, 59, 51],
       [49, 67,  0, 88, 90],
       [72, 29, 48, 27, 36],
       [77, 23, 77, 39, 95]])

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [34]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [35]:
np.random.seed(13)
np.random.randn(5,5)

array([[-0.71239066,  0.75376638, -0.04450308,  0.45181234,  1.34510171],
       [ 0.53233789,  1.3501879 ,  0.86121137,  1.47868574, -1.04537713],
       [-0.78898902, -1.26160595,  0.56284679, -0.24332625,  0.9137407 ],
       [ 0.31735092,  0.12730328,  2.15038297,  0.60628866, -0.02677165],
       [-0.98416078,  1.19070527,  0.95283061, -1.08718159, -0.14521133]])

In [36]:
np.random.seed(13)
np.random.randn(5,5)

array([[-0.71239066,  0.75376638, -0.04450308,  0.45181234,  1.34510171],
       [ 0.53233789,  1.3501879 ,  0.86121137,  1.47868574, -1.04537713],
       [-0.78898902, -1.26160595,  0.56284679, -0.24332625,  0.9137407 ],
       [ 0.31735092,  0.12730328,  2.15038297,  0.60628866, -0.02677165],
       [-0.98416078,  1.19070527,  0.95283061, -1.08718159, -0.14521133]])

In [15]:
np.array([0,10])

array([ 0, 10])

In [16]:
np.array([0,3])

array([0, 3])

In [39]:
np.arange(0,24, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [41]:
np.arange(0,24,3.2,float)

array([ 0. ,  3.2,  6.4,  9.6, 12.8, 16. , 19.2, 22.4])

In [42]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [43]:
np.arange(0,25,5)

array([ 0,  5, 10, 15, 20])

In [44]:
np.random.seed(23)
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr = np.arange(0,25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr.reshape(6,6)

ValueError: cannot reshape array of size 25 into shape (6,6)

In [50]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr = np.random.randint(0,201,20)

In [54]:
ranarr

array([ 39,  90, 153, 179,   6, 123, 173,  12,  49, 194, 197, 192,  12,
        21,  48,  41,  79,  90, 190,  57])

In [55]:
ranarr.max()

197

In [56]:
ranarr.argmax()

10

In [57]:
ranarr.min()
ranarr.argmin()

4

In [58]:
ranarr.dtype()

TypeError: 'numpy.dtype[int32]' object is not callable

In [1]:
ranarr.dtype

NameError: name 'ranarr' is not defined

In [2]:
import numpy as np

In [3]:
ranarr = np.random.rand(0,25,4)

In [4]:
ranarr

array([], shape=(0, 25, 4), dtype=float64)

In [5]:
ranarr = np.random.rand(3,3)

In [6]:
ranarr


array([[0.42608822, 0.17993775, 0.58252145],
       [0.37565727, 0.52439461, 0.29110959],
       [0.1598532 , 0.15997917, 0.57657185]])

In [7]:
ranarr.dtype

dtype('float64')

In [8]:
ranarr = np.random.randint(0,25,(3,3))

In [9]:
ranarr

array([[20,  9,  4],
       [21, 18,  1],
       [16, 11,  9]])

In [10]:
ranarr.dtype

dtype('int32')

In [11]:
arr

NameError: name 'arr' is not defined

In [12]:
ranarr.shape

(3, 3)

In [13]:
ranarr.reshape(3,4)

ValueError: cannot reshape array of size 9 into shape (3,4)

In [14]:
ranarr.reshape(9)

array([20,  9,  4, 21, 18,  1, 16, 11,  9])

In [15]:
ranarr.reshape(1,9)

array([[20,  9,  4, 21, 18,  1, 16, 11,  9]])

In [16]:
ranarr.reshape(9,1)

array([[20],
       [ 9],
       [ 4],
       [21],
       [18],
       [ 1],
       [16],
       [11],
       [ 9]])

In [17]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
arr = np.arange(0,20)

In [19]:
arr[8]

8

In [20]:
arr[ : 5]

array([0, 1, 2, 3, 4])

In [21]:
arr[11:16]

array([11, 12, 13, 14, 15])

In [22]:
arr[7:]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
arr[0:8] = 27

In [24]:
arr

array([27, 27, 27, 27, 27, 27, 27, 27,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
slice_of_arr = arr[0:11]

In [26]:
slice_of_arr[0:8] = 29

In [27]:
slice_of_arr

array([29, 29, 29, 29, 29, 29, 29, 29,  8,  9, 10])

In [28]:
arr

array([29, 29, 29, 29, 29, 29, 29, 29,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr_copy = arr.copy()

In [30]:
arr_copy[0:7] = 76

In [31]:
arr_copy

array([76, 76, 76, 76, 76, 76, 76, 29,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
arr

array([29, 29, 29, 29, 29, 29, 29, 29,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
arr.reshape(5,4)

array([[29, 29, 29, 29],
       [29, 29, 29, 29],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
arr_2d = arr.reshape(5,4)

In [35]:
arr_2d

array([[29, 29, 29, 29],
       [29, 29, 29, 29],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
arr_2d[0]

array([29, 29, 29, 29])

In [37]:
arr_2d[2,3]

11

In [38]:
arr[,3]

SyntaxError: invalid syntax (4178344395.py, line 1)

In [39]:
arr_2d[:2]

array([[29, 29, 29, 29],
       [29, 29, 29, 29]])

In [40]:
arr_2d[:2,1:]

array([[29, 29, 29],
       [29, 29, 29]])

In [41]:
arr_2d[:2,2:]

array([[29, 29],
       [29, 29]])

In [42]:
arr = np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
bool_arr = arr > 4

In [46]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr(bool_arr)

TypeError: 'numpy.ndarray' object is not callable

In [48]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[arr<7]

array([1, 2, 3, 4, 5, 6])

In [50]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [51]:
condition = dice_rolls[dice_rolls>2].shape

In [52]:
condition

(19,)

In [53]:
x = condition[0]

In [54]:
x

19

In [55]:
arr = np.arange[0,10]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr = np.arange(0,10)

In [58]:
arr = arr + 5

In [59]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
arr - 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
arr + arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [63]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
1/arr

array([0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857])

In [66]:
arr = np.arange(0,10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr / arr

C:\Users\user\AppData\Local\Temp\ipykernel_12972\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
1 / arr

C:\Users\user\AppData\Local\Temp\ipykernel_12972\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.log(arr)

C:\Users\user\AppData\Local\Temp\ipykernel_12972\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [72]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [74]:
np.cot(arr)

AttributeError: module 'numpy' has no attribute 'cot'

In [75]:
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [76]:
arr.var()

8.25

In [77]:
arr.std()

2.8722813232690143

In [78]:
arr2D = np.arange(1,26).reshape(5,5)

In [79]:
arr2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
arr2D.sum()

325

In [81]:
arr[0:].sum()

45

In [82]:
arr2D.sum(axis=0)

array([55, 60, 65, 70, 75])

In [83]:
arr2D.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [84]:
arr = np.random.randn()

In [85]:
arr

-1.6223757326672374

In [86]:
np.random.randn(10)

array([-0.04143227,  0.19517913,  0.51850076,  1.21064922,  1.79798386,
        1.21629225,  0.70155794, -0.67174619, -1.10078162, -0.05258745])

In [87]:
arr = np.random.randn(3,3)

In [88]:
arr

array([[-0.24075842,  0.36570509, -1.5218674 ],
       [-1.35889655, -0.81912993, -0.83741892],
       [-0.0331045 ,  0.60995577, -1.1970348 ]])

In [89]:
arr.std()

0.7240780959898344

In [90]:
arr.var()

0.5242890890922639

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
np.arange(0,25,4,dtype=float)

array([ 0.,  4.,  8., 12., 16., 20., 24.])

In [5]:
arr = np.arange(1,26)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
arr.argmax()

24

In [9]:
arr.std()

7.211102550927978

In [10]:
arr.var()

52.0

In [12]:
arr2 = np.random.rand()

In [13]:
arr2

0.3338290658825871

In [27]:
arr2 = np.random.rand(16)

In [28]:
arr2

array([0.90566364, 0.7900631 , 0.85177046, 0.14632642, 0.91641082,
       0.54298535, 0.081222  , 0.54462984, 0.00404747, 0.53151736,
       0.20148078, 0.83395022, 0.02029174, 0.6750392 , 0.88120481,
       0.93616349])

In [29]:
arr2.reshape(4,4)

array([[0.90566364, 0.7900631 , 0.85177046, 0.14632642],
       [0.91641082, 0.54298535, 0.081222  , 0.54462984],
       [0.00404747, 0.53151736, 0.20148078, 0.83395022],
       [0.02029174, 0.6750392 , 0.88120481, 0.93616349]])

In [30]:
arr3 = np.random.rand(16)

In [31]:
arr2 = arr2.reshape(4,4)
arr3 = arr3.reshape(4,4)

In [19]:
arr2
arr3

array([[0.50810934, 0.2495567 , 0.33225831, 0.03382557],
       [0.43438228, 0.31848086, 0.05050765, 0.99933326],
       [0.72575195, 0.48431853, 0.43736646, 0.26857338],
       [0.94834853, 0.42633822, 0.41351182, 0.31147072]])

In [20]:
arr2

array([[0.72403059, 0.09352761, 0.7543773 , 0.90641274],
       [0.48857353, 0.82071606, 0.73494101, 0.82819379],
       [0.12714392, 0.52579757, 0.1358636 , 0.48744069],
       [0.67977704, 0.09512551, 0.70664752, 0.37793009]])

In [21]:
arr3

array([[0.50810934, 0.2495567 , 0.33225831, 0.03382557],
       [0.43438228, 0.31848086, 0.05050765, 0.99933326],
       [0.72575195, 0.48431853, 0.43736646, 0.26857338],
       [0.94834853, 0.42633822, 0.41351182, 0.31147072]])

In [32]:
arr4 = arr2 + arr3

In [23]:
arr4

array([[1.23213993, 0.34308431, 1.08663561, 0.9402383 ],
       [0.92295581, 1.13919693, 0.78544866, 1.82752704],
       [0.85289587, 1.01011611, 0.57323006, 0.75601407],
       [1.62812558, 0.52146373, 1.12015934, 0.68940081]])

In [23]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [24]:
np.linspace(0,25,4)

array([ 0.        ,  8.33333333, 16.66666667, 25.        ])

In [33]:
arr2.sum()

8.862766696037397

In [34]:
arr2

array([[0.90566364, 0.7900631 , 0.85177046, 0.14632642],
       [0.91641082, 0.54298535, 0.081222  , 0.54462984],
       [0.00404747, 0.53151736, 0.20148078, 0.83395022],
       [0.02029174, 0.6750392 , 0.88120481, 0.93616349]])

In [35]:
arr2.sum(0)

array([1.84641367, 2.539605  , 2.01567805, 2.46106997])

In [36]:
arr2.sum(1)

array([2.69382362, 2.08524801, 1.57099582, 2.51269924])

In [1]:
arr3.all(0)

NameError: name 'arr3' is not defined

In [1]:
arr2 = np.random.randint(0,20).reshape(4,5)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
arr2 = np.random.randint(0,20,(5,5))

In [4]:
arr2

array([[19,  1, 15,  7, 17],
       [17, 13, 18, 15, 18],
       [18, 18,  7, 16, 16],
       [ 8, 17,  4,  6, 14],
       [ 2, 10, 13,  8,  5]])

In [5]:
arr2.std()

5.585123096226259

In [6]:
arr2.var()

31.1936

In [7]:
arr2

array([[19,  1, 15,  7, 17],
       [17, 13, 18, 15, 18],
       [18, 18,  7, 16, 16],
       [ 8, 17,  4,  6, 14],
       [ 2, 10, 13,  8,  5]])